name: Generate and Update PNG Icons

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  actions: write

env:
  LAST_COMMIT: ${{ vars.LAST_PROCESSED_COMMIT }}

jobs:
  check-and-generate-pngs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v2

    - name: Get latest commit from microsoft/fluentui-system-icons
      id: get_latest_commit
      run: |
        LATEST_COMMIT=$(curl -s "https://api.github.com/repos/microsoft/fluentui-system-icons/commits/main" | jq -r .sha)
        echo "latest_commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT

    - name: Check if update is needed
      id: check_update
      run: |
        if [ -z "${{ env.LAST_COMMIT }}" ] || [ "${{ steps.get_latest_commit.outputs.latest_commit }}" != "${{ env.LAST_COMMIT }}" ]; then
          echo "update_needed=true" >> $GITHUB_OUTPUT
        else
          echo "update_needed=false" >> $GITHUB_OUTPUT
        fi

    - name: Checkout microsoft/fluentui-system-icons
      if: steps.check_update.outputs.update_needed == 'true'
      uses: actions/checkout@v2
      with:
        repository: microsoft/fluentui-system-icons
        path: fluentui-temp

    - name: Setup Node.js
      if: steps.check_update.outputs.update_needed == 'true'
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      if: steps.check_update.outputs.update_needed == 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y librsvg2-bin imagemagick

    - name: Generate PNGs
      if: steps.check_update.outputs.update_needed == 'true'
      run: |
        mkdir -p assets
        cd fluentui-temp/assets
        find . -type d -name "SVG" | while read -r svg_dir; do
          icon_folder=$(dirname "$svg_dir")
          icon_name=$(basename "$icon_folder")
          mkdir -p "../../assets/${icon_name}/png"
          for svg_file in "${svg_dir}"/*.svg; do
            filename=$(basename "$svg_file" .svg)
            for size in 16 32 64 128; do
              rsvg-convert -w $size -h $size "$svg_file" | \
              convert - -background none -gravity center -extent ${size}x${size} "../../assets/${icon_name}/png/${filename}-${size}.png"
            done
          done
        done

    - name: Remove temporary files
      if: steps.check_update.outputs.update_needed == 'true'
      run: rm -rf fluentui-temp

    - name: Update last processed commit
      if: steps.check_update.outputs.update_needed == 'true'
      run: |
        echo "LAST_PROCESSED_COMMIT=${{ steps.get_latest_commit.outputs.latest_commit }}" >> $GITHUB_ENV

    - name: Commit and push changes
      if: steps.check_update.outputs.update_needed == 'true'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add assets
        git commit -m "🎨 Refresh PNG icons" || echo "👌 All icons up-to-date, nothing to commit"
        git push

    - name: Update repository variable
      if: steps.check_update.outputs.update_needed == 'true'
      env:
        GH_TOKEN: ${{ secrets.PAT }}
      run: |
        curl -X PATCH \
          -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/variables/LAST_PROCESSED_COMMIT \
          -d "{\"name\":\"LAST_PROCESSED_COMMIT\",\"value\":\"${{ steps.get_latest_commit.outputs.latest_commit }}\"}"
